apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "app.shortname" . }}-api-configmap
  labels:
  {{- include "api.labels" . | nindent 4 }}
data:
  {{- if .Values.api.environment }}
  {{- range $key, $val := .Values.api.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  SPRING_PROFILES_ACTIVE: prod
  PORT: {{ .Values.api.containerPorts.http | quote}}
  SECURITY_AUTHENTICATION_TOKEN_BASE64_SECRET: ${TOKEN_SECRET}
  SECURITY_CIPHER_BASE64_SECRET: ${CIPHER_SECRET}
  SECURITY_AUTHENTICATION_TOKEN_TOKEN_VALIDITY_IN_SECONDS: {{ .Values.token.tokenValidityInSeconds| quote}}
  SPRING_DATA_MONGODB_URI: mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@{{ template "app.shortname" . }}-mongodb:{{ .Values.mongodb.service.port }}/demo