apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.shortname" . }}-cipher-secret
  labels:
    {{- include "api.labels" . | nindent 4 }}
type: Opaque
data:
  CIPHER_SECRET: c2VjdXJlQ0RDS2V5