version: '3.8'

volumes:
  mongodb:

networks:
  test:
    name: backend_test

services:
  api:
    image: suayb/spring-native-reactive-graphql-example
    restart: unless-stopped
    container_name: api
    depends_on:
     - mongodb
    networks:
      - test
    environment:
      - PORT
      - SPRING_DATA_MONGODB_URI
      - SECURITY_AUTHENTICATION_TOKEN_BASE64_SECRET
      - SECURITY_AUTHENTICATION_TOKEN_TOKEN_VALIDITY_IN_SECONDS
      - SECURITY_CIPHER_BASE64_SECRET
    ports:
      - "9091:9091"

  mongodb:
    image: mongo:5.0
    restart: unless-stopped
    container_name: mongodb
    networks:
      - test
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGODB_DATABASE
      - MONGODB_USERNAME
      - MONGODB_PASSWORD
    volumes:
      - ./mongodb/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - mongodb:/data/db
    ports:
      - "27017:27017"