global:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  imagePullSecrets: []

istio:
  enabled: false
  gateway:
    selector: ingressgateway
    httpsRedirect: false

token:
  tokenValidityInSeconds: 86400

mongodb:
  enabled: true
  replicaCount: 1
  architecture: standalone
  image:
    tag: 4.4.13-debian-10-r52
  auth:
    rootUser: root
    rootPassword: g44bsljDAi5nbWjf
    usernames:
      - user
    passwords:
      - iXCjXb7e2yjJbjRu
    databases:
      - demo
  service:
    port: 27017
    type: NodePort
    nodePort: 30017

api:
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPU: 50
    targetMemory: 50
  replicaCount: 2
  containerPorts:
    http: 9090
  image:
    repository: suayb/spring-native-reactive-graphql-example
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
    clusterIP:
    loadBalancerIP:
  environment:
  ingress:
    enabled: true
    certManager: false
    annotations:
      kubernetes.io/ingress.class: "nginx"
    path: /
    hostName: spring-native-reactive-graphql-api.susimsek.github.io
    tls: []
  istio:
    gateway:
      hostName: spring-native-reactive-graphql-api.susimsek.github.io
      path: /
      tls:
        enabled: false
        secretName:
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  readinessProbe:
    enabled: true
    httpGet:
      path: /actuator/health/readiness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 6
    successThreshold: 1
  livenessProbe:
    enabled: true
    httpGet:
      path: /actuator/health/liveness
      port: http
      scheme: HTTP
      httpHeaders: [ ]
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
    successThreshold: 1
  customLivenessProbe: { }
  customReadinessProbe: { }
  extraVolumeMounts: []
  extraVolumes: []